// The service worker: what makes this an app you can open with no signal.
//
// The game has never needed the network for anything — no API, no CDN, no
// fonts, not one byte fetched at runtime — and yet it could not start without
// a round trip to a server. For a game built around leaving and coming back,
// that was the last thing standing between it and being an app.
//
// The strategy is deliberately the simplest one that is correct:
//
//   PRECACHE EVERYTHING, then serve cache-first, and never cache at runtime.
//   The app is 40 small files and no images. There is no long tail to fetch
//   lazily and no state where half of it is cached and half is not.
//
// The asset list and version come from sw-precache.js, which is generated by
// tools/build-precache.mjs and checked by tests/pwa.test.js.

importScripts('./sw-precache.js');

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // `cache: 'reload'` so a redeploy actually fetches new bytes instead of
    // filling the new cache from the HTTP cache's copy of the old ones.
    await cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' })));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // The new cache is fully populated before this runs, so dropping the old
    // ones can never leave a version of the app that is missing pieces.
    const names = await caches.keys();
    await Promise.all(
      names.filter((name) => name.startsWith('ks-') && name !== VERSION)
        .map((name) => caches.delete(name))
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Any navigation lands on the app shell. Resolved against the worker's own
  // scope so this is correct under a GitHub Pages subpath as well as at a root.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const shell = await caches.match(new URL('./index.html', self.registration.scope));
      return shell ?? fetch(request);
    })());
    return;
  }

  event.respondWith((async () => {
    const hit = await caches.match(request, { ignoreSearch: true });
    if (hit) return hit;
    try {
      return await fetch(request);
    } catch {
      // Offline and not precached: there is nothing useful to say, and a thrown
      // fetch is a clearer signal to the page than a fabricated response.
      return Response.error();
    }
  })());
});

// The page asks for this only when the player accepts an update, so a new
// version never replaces a running game mid-session.
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});
